# Generated by Django 3.1.7 on 2021-05-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('discription', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('All', 'All')], default='All', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('auction_Listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('bids_listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bid', to='auctions.listing')),
            ],
        ),
    ]
