# Generated by Django 3.1.7 on 2021-05-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210524_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='upload',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
