# Generated by Django 3.1.7 on 2021-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='upload',
            field=models.ImageField(blank=True, upload_to='auctions/static/pics'),
        ),
    ]
