# Generated by Django 3.1.7 on 2021-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210525_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='upload',
            field=models.ImageField(blank=True, upload_to='auctions/static/auctions/pics'),
        ),
    ]
