# Generated by Django 3.1.7 on 2021-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210525_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='upload',
            field=models.ImageField(blank=True, upload_to='auctions/pics'),
        ),
    ]
