# Generated by Django 3.1.7 on 2021-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imagename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
