# Generated by Django 3.1.7 on 2021-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_bid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
