# Generated by Django 3.1.7 on 2021-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210527_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
