# Generated by Django 3.1.7 on 2021-05-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auction_Listing',
            new_name='comment_Listing',
        ),
    ]
