# Generated by Django 3.1.7 on 2021-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210529_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Books', 'Books')], default='All', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imagelink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imagename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
